services:
  postgres:
    image: postgres:16
    container_name: musicfy_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: musicfy
    ports:
      - "5433:5432"  # ← MUDOU de 5432 para 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: