"""Add firebase_uid, address, stripe_session_id

Revision ID: 4015f25441eb
Revises: 87d2a0ae70c3
Create Date: 2026-04-24 18:34:21.530592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4015f25441eb'
down_revision: Union[str, None] = '87d2a0ae70c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
